version: '3.7'

services:
  worker1:
    image: app-worker
    restart: unless-stopped
    networks:
      - app-network

  worker2:
    image: app-worker
    restart: unless-stopped
    networks:
      - app-network

  master:
    image: app-master
    restart: unless-stopped
    depends_on:
      - worker1
      - worker2
    command: sh -c "sleep 10 && python master.py"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

